version: '3.1'

services:
  db:
    image: 'postgres'
    restart: always
    hostname: 'postgres'
    container_name: 'postgres_db'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}